apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-19T13:58:55Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "7726"
  uid: 2909968d-c34a-42f6-aba9-6cc50d6d0854
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.109.108.97
  clusterIPs:
  - 10.109.108.97
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32597
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
